### ISSUE TITLE
Add  subsite Privacy Policy / Datenschutz Hinweise

### ISSUE THREAD

**Issue by DerKleineLeif** [butzbach-spielt/butzbach-spielt-website#33]
add a site Privacy Policy like 
https://www.heise.de/Datenschutzerklaerung-der-Heise-Medien-GmbH-Co-KG-4860.html
or
https://www.radio-wewewe.de/datenschutz/

to be compliant with GDPDR / DSGVO 

Useful content generator:
https://datenschutz-generator.de

### ToDos

- [x] create and integrate subsite
- [x] check integrated external services e.g. fonts
- [x] create site content

**Comment by DerKleineLeif** [comment]
ToDos

- [ ] create and integrate subsite
- [ ] create site content

**Comment by Morl99** [comment]
The only external content that we include is uploadcare as a media hoster for our images. They are gdpr compliant (eu privacy shield) and need to be included in the data privacy statement on our website. Other than that, it should be the usual.

Of course the site itself is hosted on netlify, so that will likely also need to be taken into account.

**Comment by Morl99** [comment]
I created a first version of the data privacy site in the branch where I also created the imprint, as I needed the footer and basic structure to exist. Check it out in #42
